title: Philipp Ratz
description: > # this means to ignore newlines until "baseurl:"
  Data Scientist and Economist. I like to write things down to really understand them.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phi-ra.github.io" # the base hostname & protocol for your site, e.g. 

# Author Settings
author: Philipp Ratz # add your name
author-img: phi_ra_head.jpg # add your photo
about-author:   Data Scientist and Economist. I like to write things down to really understand them.
# add description
#social-twitter:  # add your Twitter handle
#social-facebook:  # add your Facebook handle
social-github: phi-ra # ig handle
social-linkedin: philippratz # add your Linkedin handle
#social-email:  # add your Email address

# Disqus

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
